//===----------------------------------------------------------------------===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//

// WARNING: This test was generated by generate_feature_test_macro_components.py
// and should not be edited manually.

// <execution>

// Test the feature test macros defined by <execution>

// clang-format off

#include <execution>
#include "test_macros.h"

#if TEST_STD_VER < 14

#  ifdef __cpp_lib_counting_scope
#    error "__cpp_lib_counting_scope should not be defined before c++26"
#  endif

#  ifdef __cpp_lib_execution
#    error "__cpp_lib_execution should not be defined before c++17"
#  endif

#  ifdef __cpp_lib_freestanding_execution
#    error "__cpp_lib_freestanding_execution should not be defined before c++26"
#  endif

#  ifdef __cpp_lib_parallel_scheduler
#    error "__cpp_lib_parallel_scheduler should not be defined before c++26"
#  endif

#  ifdef __cpp_lib_senders
#    error "__cpp_lib_senders should not be defined before c++26"
#  endif

#  ifdef __cpp_lib_task
#    error "__cpp_lib_task should not be defined before c++26"
#  endif

#elif TEST_STD_VER == 14

#  ifdef __cpp_lib_counting_scope
#    error "__cpp_lib_counting_scope should not be defined before c++26"
#  endif

#  ifdef __cpp_lib_execution
#    error "__cpp_lib_execution should not be defined before c++17"
#  endif

#  ifdef __cpp_lib_freestanding_execution
#    error "__cpp_lib_freestanding_execution should not be defined before c++26"
#  endif

#  ifdef __cpp_lib_parallel_scheduler
#    error "__cpp_lib_parallel_scheduler should not be defined before c++26"
#  endif

#  ifdef __cpp_lib_senders
#    error "__cpp_lib_senders should not be defined before c++26"
#  endif

#  ifdef __cpp_lib_task
#    error "__cpp_lib_task should not be defined before c++26"
#  endif

#elif TEST_STD_VER == 17

#  ifdef __cpp_lib_counting_scope
#    error "__cpp_lib_counting_scope should not be defined before c++26"
#  endif

#  if !defined(_LIBCPP_VERSION) || _LIBCPP_HAS_EXPERIMENTAL_PSTL
#    ifndef __cpp_lib_execution
#      error "__cpp_lib_execution should be defined in c++17"
#    endif
#    if __cpp_lib_execution != 201603L
#      error "__cpp_lib_execution should have the value 201603L in c++17"
#    endif
#  else
#    ifdef __cpp_lib_execution
#      error "__cpp_lib_execution should not be defined when the requirement '!defined(_LIBCPP_VERSION) || _LIBCPP_HAS_EXPERIMENTAL_PSTL' is not met!"
#    endif
#  endif

#  ifdef __cpp_lib_freestanding_execution
#    error "__cpp_lib_freestanding_execution should not be defined before c++26"
#  endif

#  ifdef __cpp_lib_parallel_scheduler
#    error "__cpp_lib_parallel_scheduler should not be defined before c++26"
#  endif

#  ifdef __cpp_lib_senders
#    error "__cpp_lib_senders should not be defined before c++26"
#  endif

#  ifdef __cpp_lib_task
#    error "__cpp_lib_task should not be defined before c++26"
#  endif

#elif TEST_STD_VER == 20

#  ifdef __cpp_lib_counting_scope
#    error "__cpp_lib_counting_scope should not be defined before c++26"
#  endif

#  if !defined(_LIBCPP_VERSION) || _LIBCPP_HAS_EXPERIMENTAL_PSTL
#    ifndef __cpp_lib_execution
#      error "__cpp_lib_execution should be defined in c++20"
#    endif
#    if __cpp_lib_execution != 201902L
#      error "__cpp_lib_execution should have the value 201902L in c++20"
#    endif
#  else
#    ifdef __cpp_lib_execution
#      error "__cpp_lib_execution should not be defined when the requirement '!defined(_LIBCPP_VERSION) || _LIBCPP_HAS_EXPERIMENTAL_PSTL' is not met!"
#    endif
#  endif

#  ifdef __cpp_lib_freestanding_execution
#    error "__cpp_lib_freestanding_execution should not be defined before c++26"
#  endif

#  ifdef __cpp_lib_parallel_scheduler
#    error "__cpp_lib_parallel_scheduler should not be defined before c++26"
#  endif

#  ifdef __cpp_lib_senders
#    error "__cpp_lib_senders should not be defined before c++26"
#  endif

#  ifdef __cpp_lib_task
#    error "__cpp_lib_task should not be defined before c++26"
#  endif

#elif TEST_STD_VER == 23

#  ifdef __cpp_lib_counting_scope
#    error "__cpp_lib_counting_scope should not be defined before c++26"
#  endif

#  if !defined(_LIBCPP_VERSION) || _LIBCPP_HAS_EXPERIMENTAL_PSTL
#    ifndef __cpp_lib_execution
#      error "__cpp_lib_execution should be defined in c++23"
#    endif
#    if __cpp_lib_execution != 201902L
#      error "__cpp_lib_execution should have the value 201902L in c++23"
#    endif
#  else
#    ifdef __cpp_lib_execution
#      error "__cpp_lib_execution should not be defined when the requirement '!defined(_LIBCPP_VERSION) || _LIBCPP_HAS_EXPERIMENTAL_PSTL' is not met!"
#    endif
#  endif

#  ifdef __cpp_lib_freestanding_execution
#    error "__cpp_lib_freestanding_execution should not be defined before c++26"
#  endif

#  ifdef __cpp_lib_parallel_scheduler
#    error "__cpp_lib_parallel_scheduler should not be defined before c++26"
#  endif

#  ifdef __cpp_lib_senders
#    error "__cpp_lib_senders should not be defined before c++26"
#  endif

#  ifdef __cpp_lib_task
#    error "__cpp_lib_task should not be defined before c++26"
#  endif

#elif TEST_STD_VER > 23

#  ifndef __cpp_lib_counting_scope
#    error "__cpp_lib_counting_scope should be defined in c++26"
#  endif
#  if __cpp_lib_counting_scope != 202506L
#    error "__cpp_lib_counting_scope should have the value 202506L in c++26"
#  endif

#  if !defined(_LIBCPP_VERSION) || _LIBCPP_HAS_EXPERIMENTAL_PSTL
#    ifndef __cpp_lib_execution
#      error "__cpp_lib_execution should be defined in c++26"
#    endif
#    if __cpp_lib_execution != 201902L
#      error "__cpp_lib_execution should have the value 201902L in c++26"
#    endif
#  else
#    ifdef __cpp_lib_execution
#      error "__cpp_lib_execution should not be defined when the requirement '!defined(_LIBCPP_VERSION) || _LIBCPP_HAS_EXPERIMENTAL_PSTL' is not met!"
#    endif
#  endif

#  ifndef __cpp_lib_freestanding_execution
#    error "__cpp_lib_freestanding_execution should be defined in c++26"
#  endif
#  if __cpp_lib_freestanding_execution != 202502L
#    error "__cpp_lib_freestanding_execution should have the value 202502L in c++26"
#  endif

#  if !defined(_LIBCPP_VERSION) || _LIBCPP_HAS_THREADS
#    ifndef __cpp_lib_parallel_scheduler
#      error "__cpp_lib_parallel_scheduler should be defined in c++26"
#    endif
#    if __cpp_lib_parallel_scheduler != 202506L
#      error "__cpp_lib_parallel_scheduler should have the value 202506L in c++26"
#    endif
#  else
#    ifdef __cpp_lib_parallel_scheduler
#      error "__cpp_lib_parallel_scheduler should not be defined when the requirement '!defined(_LIBCPP_VERSION) || _LIBCPP_HAS_THREADS' is not met!"
#    endif
#  endif

#  ifndef __cpp_lib_senders
#    error "__cpp_lib_senders should be defined in c++26"
#  endif
#  if __cpp_lib_senders != 202506L
#    error "__cpp_lib_senders should have the value 202506L in c++26"
#  endif

#  ifndef __cpp_lib_task
#    error "__cpp_lib_task should be defined in c++26"
#  endif
#  if __cpp_lib_task != 202506L
#    error "__cpp_lib_task should have the value 202506L in c++26"
#  endif

#endif // TEST_STD_VER > 23

// clang-format on
