//===----------------------------------------------------------------------===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//

// WARNING: This test was generated by generate_feature_test_macro_components.py
// and should not be edited manually.

// <meta>

// Test the feature test macros defined by <meta>

// clang-format off

#include <meta>
#include "test_macros.h"

#if TEST_STD_VER < 14

#  ifdef __cpp_lib_reflection
#    error "__cpp_lib_reflection should not be defined before c++26"
#  endif

#elif TEST_STD_VER == 14

#  ifdef __cpp_lib_reflection
#    error "__cpp_lib_reflection should not be defined before c++26"
#  endif

#elif TEST_STD_VER == 17

#  ifdef __cpp_lib_reflection
#    error "__cpp_lib_reflection should not be defined before c++26"
#  endif

#elif TEST_STD_VER == 20

#  ifdef __cpp_lib_reflection
#    error "__cpp_lib_reflection should not be defined before c++26"
#  endif

#elif TEST_STD_VER == 23

#  ifdef __cpp_lib_reflection
#    error "__cpp_lib_reflection should not be defined before c++26"
#  endif

#elif TEST_STD_VER > 23

#  if __has_feature(reflection)
#    ifndef __cpp_lib_reflection
#      error "__cpp_lib_reflection should be defined in c++26"
#    endif
#    if __cpp_lib_reflection != 202603L
#      error "__cpp_lib_reflection should have the value 202603L in c++26"
#    endif
#  else
#    ifdef __cpp_lib_reflection
#      error "__cpp_lib_reflection should not be defined when the requirement '__has_feature(reflection)' is not met!"
#    endif
#  endif

#endif // TEST_STD_VER > 23

// clang-format on
