//===----------------------------------------------------------------------===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//

// WARNING: This test was generated by generate_feature_test_macro_components.py
// and should not be edited manually.

// <simd>

// Test the feature test macros defined by <simd>

// clang-format off

#include <simd>
#include "test_macros.h"

#if TEST_STD_VER < 14

#  ifdef __cpp_lib_simd
#    error "__cpp_lib_simd should not be defined before c++26"
#  endif

#  ifdef __cpp_lib_simd_complex
#    error "__cpp_lib_simd_complex should not be defined before c++26"
#  endif

#  ifdef __cpp_lib_simd_permutations
#    error "__cpp_lib_simd_permutations should not be defined before c++26"
#  endif

#elif TEST_STD_VER == 14

#  ifdef __cpp_lib_simd
#    error "__cpp_lib_simd should not be defined before c++26"
#  endif

#  ifdef __cpp_lib_simd_complex
#    error "__cpp_lib_simd_complex should not be defined before c++26"
#  endif

#  ifdef __cpp_lib_simd_permutations
#    error "__cpp_lib_simd_permutations should not be defined before c++26"
#  endif

#elif TEST_STD_VER == 17

#  ifdef __cpp_lib_simd
#    error "__cpp_lib_simd should not be defined before c++26"
#  endif

#  ifdef __cpp_lib_simd_complex
#    error "__cpp_lib_simd_complex should not be defined before c++26"
#  endif

#  ifdef __cpp_lib_simd_permutations
#    error "__cpp_lib_simd_permutations should not be defined before c++26"
#  endif

#elif TEST_STD_VER == 20

#  ifdef __cpp_lib_simd
#    error "__cpp_lib_simd should not be defined before c++26"
#  endif

#  ifdef __cpp_lib_simd_complex
#    error "__cpp_lib_simd_complex should not be defined before c++26"
#  endif

#  ifdef __cpp_lib_simd_permutations
#    error "__cpp_lib_simd_permutations should not be defined before c++26"
#  endif

#elif TEST_STD_VER == 23

#  ifdef __cpp_lib_simd
#    error "__cpp_lib_simd should not be defined before c++26"
#  endif

#  ifdef __cpp_lib_simd_complex
#    error "__cpp_lib_simd_complex should not be defined before c++26"
#  endif

#  ifdef __cpp_lib_simd_permutations
#    error "__cpp_lib_simd_permutations should not be defined before c++26"
#  endif

#elif TEST_STD_VER > 23

#  ifndef __cpp_lib_simd
#    error "__cpp_lib_simd should be defined in c++26"
#  endif
#  if __cpp_lib_simd != 202603L
#    error "__cpp_lib_simd should have the value 202603L in c++26"
#  endif

#  ifndef __cpp_lib_simd_complex
#    error "__cpp_lib_simd_complex should be defined in c++26"
#  endif
#  if __cpp_lib_simd_complex != 202502L
#    error "__cpp_lib_simd_complex should have the value 202502L in c++26"
#  endif

#  ifndef __cpp_lib_simd_permutations
#    error "__cpp_lib_simd_permutations should be defined in c++26"
#  endif
#  if __cpp_lib_simd_permutations != 202506L
#    error "__cpp_lib_simd_permutations should have the value 202506L in c++26"
#  endif

#endif // TEST_STD_VER > 23

// clang-format on

